name: "Run tests against latest Gradle RC/nightly"

on:
  schedule:
    - cron: '3 1 * * 5'
  workflow_dispatch:
    inputs:
      gradle-version:
        description: "A specific Gradle version to test against"
        default: "-"
        required: false

jobs:
  build:
    uses: SpongePowered/.github/.github/workflows/shared-test-gradle-rc.yaml@master
    with:
      gradle_version: "${{ inputs.gradle-version }}"
      injected_version_path: 'plugin-development/src/functionalTest/resources/'
